"""update models contact/add table User/add table UserToken

Revision ID: 739e79a9db43
Revises: caf46c06e1f5
Create Date: 2024-12-06 15:58:47.636879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739e79a9db43'
down_revision: Union[str, None] = 'caf46c06e1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_token_id'), 'user_token', ['id'], unique=False)
    op.add_column('contact', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('contact', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('contact', sa.Column('users_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contact', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'users_id')
    op.drop_column('contact', 'updated_at')
    op.drop_column('contact', 'created_at')
    op.drop_index(op.f('ix_user_token_id'), table_name='user_token')
    op.drop_table('user_token')
    op.drop_table('users')
    # ### end Alembic commands ###
