[tool.poetry]
name = "home-work"
version = "0.1.0"
description = "CLI-asistent"
authors = ["dima cheban <dimacheban23@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
